trigger:
  - master

pr:
  autoCancel: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: "Use Node 12.13.0"
    inputs:
      versionSpec: 12.13.0
  - script: yarn
    displayName: "yarn install"
    workingDirectory: Composer
  - script: yarn build:prod
    displayName: "yarn build:prod"
    workingDirectory: Composer
  - script: yarn test:integration --record --parallel
    displayName: yarn test:integration
    workingDirectory: Composer
    continueOnError: true
    env:
      CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)
      CYPRESS_VIDEO: true
      CYPRESS_VIDEO_UPLOAD_ON_PASSES: true
