trigger:
  - master

pr:
  autoCancel: true
  branches:
    include:
      - '*'

strategy:
  parallel: 4

pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: NodeTool@0
    displayName: "Use Node 12.13.0"
    inputs:
      versionSpec: 12.13.0
  - task: CacheBeta@1
    inputs:
      key: yarn | $(Agent.OS) | Composer/yarn.lock
      path: $(YARN_CACHE_FOLDER)
      restoreKeys: |
        yarn | $(Agent.OS)
    displayName: Cache Yarn packages
  - task: CacheBeta@1
    inputs:
      key: cypress | $(Agent.OS) | Composer/yarn.lock
      path: /home/vsts/.cache/Cypress
      restoreKeys: cypress | $(Agent.OS) | Composer/yarn.lock
    displayName: Cache Cypress binary
  - script: yarn --frozen-lockfile
    displayName: "yarn install"
    workingDirectory: Composer
  - script: yarn build
    displayName: "yarn build"
    workingDirectory: Composer
  - script: |
      npx start-server-and-test start 3000 'cypress run --browser chrome --record --parallel --ci-build-id $BUILD_BUILDNUMBER --group "Azure CI" --spec "cypress/integration/*.spec.ts"'
    displayName: yarn test:integration
    workingDirectory: Composer
    continueOnError: true
    env:
      CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)
      CYPRESS_VIDEO: true
      CYPRESS_VIDEO_UPLOAD_ON_PASSES: true
