trigger:
  - master

pr:
  autoCancel: true
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - task: NodeTool@0
    displayName: "Use Node 12.13.0"
    inputs:
      versionSpec: 12.13.0
  - task: CacheBeta@1
    inputs:
      key: yarn | $(Agent.OS) | Composer/yarn.lock
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  - script: yarn --frozen-lockfile
    displayName: "yarn install"
    workingDirectory: Composer
  - script: yarn build
    displayName: "yarn build"
    workingDirectory: Composer
  - script: yarn test:integration
    displayName: yarn test:integration
    workingDirectory: Composer
    continueOnError: true
    env:
      CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)
      CYPRESS_VIDEO: true
      CYPRESS_VIDEO_UPLOAD_ON_PASSES: true
