version: "3"
services:
  composer:
    build: Composer
    ports:
      - "3000:3000"
    volumes:
      - /srv/bot/MyBots:/MyBots
      - /srv/bot/BotProject:/BotProject
      - /srv/bot/appdata:/appdata
    environment:
      COMPOSER_BOTS_FOLDER: /Bots
      COMPOSER_RUNTIME_FOLDER: /BotProject/Templates
      COMPOSER_APP_DATA: /appdata/data.json
      BOT_ENDPOINT: http://botruntime:80
      PORT: 3000
  botruntime:
    build: BotProject/CSharp
    ports:
      - "3979:80"
    volumes:
      - /srv/bot/MyBots:/app/MyBots
  directline:
    build: offline-directline
    ports:
      - "5003:3000"
  webchat:
    ports:
      - "5002:5000"
    build: webchat

